# Numpy[Numerical Python] : Python에서 대규모 다차원 배열을 사용할 수 있도록 하는 라이브러리

In [2]:
import numpy as np

In [22]:
# List = list(range(5))

# numpy
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [24]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
np.ones(10, dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [57]:
np.empty((4,2)) 

array([[4.66273958e-310, 2.14321575e-312],
       [2.37663529e-312, 2.56761491e-312],
       [1.10343781e-312, 1.06099790e-312],
       [4.61746284e-310, 6.91426949e-310]])

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0, 10, 2) # (start, end, step) , end 포함 X

array([0, 2, 4, 6, 8])

In [28]:
np.linspace(0, 1, 5)  # (start, end, count)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.random.random( (2,2) ) # 

array([[0.4474451 , 0.86281827],
       [0.42263658, 0.01657345]])

In [31]:
 np.random.normal(0, 1, (2,2)) # (평균, 표준편차, Size)

array([[ 0.78104836,  1.47255134],
       [ 0.9759928 , -0.65288074]])

In [43]:
np.random.randint(0, 4, (2,2) ) # (start, end, Size), end 포함 X

array([[3, 3],
       [0, 0]])

In [43]:
# =============================================================================================================================

In [52]:
arr = np.random.randint(0, 10, (3, 5))
arr

array([[1, 1, 8, 4, 2],
       [6, 0, 6, 0, 3],
       [4, 6, 8, 0, 1]])

In [53]:
arr.ndim  # 2 차원

2

In [50]:
arr.shape # 구조

(3, 3)

In [55]:
arr.size  # 길이

15

In [56]:
arr.dtype # 타입

dtype('int64')

In [63]:
arr[0][::2]  # step 주어서 읽기

array([1, 8, 2])

In [ ]:
# =============================================================================================================================

In [75]:
# 구조 함수
arr = np.arange(10)
arr2 = arr.reshape( (5, 2) )  # 구조 변경
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [77]:
arr = np.arange(3)  # 0 1 2
arr2 = np.arange(3, 6)  # 3 4 5
np.concatenate([arr, arr2]) # 이어서 붙이기

array([0, 1, 2, 3, 4, 5])

In [86]:
arr = np.arange(4).reshape(2, 2)
temp = np.arange(6).reshape(3, 2)
np.concatenate([arr, temp], axis=0) # 세로 방향으로 붙임 (아래)

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3],
       [4, 5]])

In [87]:
arr = np.arange(4).reshape(2, 2)
temp = np.arange(6).reshape(2, 3)
np.concatenate([arr, temp], axis=1) # 가로 방향으로 붙임 (오른쪽)

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5]])

In [104]:
arr = np.arange(12).reshape(4, 3)
one, two = np.split(arr, [1], axis=1)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [105]:
one

array([[0],
       [3],
       [6],
       [9]])

In [106]:
two

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [ ]:
# =============================================================================================================================

In [2]:
# Numpy 연산
# +, -, *, / 모두 사용하여 연산이 가능하다.

In [3]:
import numpy as np

In [5]:
arr = np.random.randint(5, 50, size=100)
arr

array([30, 39, 46, 44,  5, 28, 44, 23, 29, 43, 39, 35,  7, 26, 33, 47, 29,
       29, 18, 20, 16, 14, 24, 47, 37, 13, 26,  7, 41,  8, 30, 13, 19, 11,
       47, 13,  5, 10, 11, 14,  7, 37, 29, 41, 24, 29, 30, 21, 17, 44, 46,
       33, 42, 34, 30, 36,  7, 28,  9, 24, 19, 28, 41, 40, 32, 22, 11, 16,
       21, 19,  6, 28, 12,  7,  9, 29, 20, 16, 28,  6,  8, 26, 49, 48, 49,
       45, 13, 31, 34, 21, 39, 16, 38, 39, 29, 49, 44, 46, 36, 33])

In [6]:
arr = arr + 5
arr

array([35, 44, 51, 49, 10, 33, 49, 28, 34, 48, 44, 40, 12, 31, 38, 52, 34,
       34, 23, 25, 21, 19, 29, 52, 42, 18, 31, 12, 46, 13, 35, 18, 24, 16,
       52, 18, 10, 15, 16, 19, 12, 42, 34, 46, 29, 34, 35, 26, 22, 49, 51,
       38, 47, 39, 35, 41, 12, 33, 14, 29, 24, 33, 46, 45, 37, 27, 16, 21,
       26, 24, 11, 33, 17, 12, 14, 34, 25, 21, 33, 11, 13, 31, 54, 53, 54,
       50, 18, 36, 39, 26, 44, 21, 43, 44, 34, 54, 49, 51, 41, 38])

In [11]:
arr = np.arange(4).reshape((2,2))
arr2 = np.random.randint(-10, -1, (2,2))

In [13]:
arr

array([[0, 1],
       [2, 3]])

In [14]:
arr2

array([[ -4,  -2],
       [ -4, -10]])

In [15]:
arr + arr2

array([[-4, -1],
       [-2, -7]])

In [106]:
# =============================================================================================================================

In [15]:
# Broadcasting : shape 구조가 다른 array간 계산한다.
# 가로 길이가 동일하거나 세로 길이가 동일해야 한다. 혹은 하나의 값만 있을 경우 그 값으로 전체를 채워서 계산

In [28]:
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
arr2 = np.arange(4)
arr2

array([0, 1, 2, 3])

In [36]:
arr + arr2

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [37]:
arr3 = np.arange(4).reshape((4,1))
arr3

array([[0],
       [1],
       [2],
       [3]])

In [38]:
arr + arr3

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

In [27]:
# =============================================================================================================================

In [27]:
# 집계 함수 : 데이터를 요약하여 통계를 볼 수 있게 도와주는 함수

In [40]:
import numpy as np
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
np.sum(arr) # 합

66

In [47]:
np.sum(arr, axis=0)

array([12, 15, 18, 21])

In [48]:
np.sum(arr, axis=1)

array([ 6, 22, 38])

In [42]:
np.mean(arr)  # 평균

5.5

In [43]:
np.max(arr) # 최대값

11

In [44]:
np.min(arr) # 최소값

0

In [52]:
np.std(arr) # 표준 편차

3.452052529534663

In [44]:
# 마스킹 연산 : array에서 True/False 판별

In [49]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
arr > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [51]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10, 11])